"""Generate the live-demo figure JSON embedded in the docs landing page.

Builds the movie-genre UpSet example in all three intersection modes and writes
them to ``docs/assets/demo.js`` as ``window.DASH_UPSET_DEMO``. The docs site is
served statically from ``docs/`` (no build step at deploy time), so this is run
locally and its output committed. Re-run it after changing the figure factory:

    pixi run python scripts/build_docs_demo.py
"""

from __future__ import annotations

import json
from pathlib import Path

import plotly.io as pio

from dash_upset import create_upset, from_counts

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "assets" / "demo.js"

# The README / landing-page example: three movie genres and their overlaps.
COUNTS = {
    "Action": 320,
    "Comedy": 290,
    "Drama": 410,
    "Action&Comedy": 84,
    "Action&Drama": 120,
    "Comedy&Drama": 96,
    "Action&Comedy&Drama": 40,
}


def build() -> None:
    data = from_counts(COUNTS)
    demos = {
        mode: json.loads(pio.to_json(create_upset(data, mode=mode, height=460)))
        for mode in ("distinct", "intersect", "union")
    }
    OUTPUT.write_text(
        "/* Generated by scripts/build_docs_demo.py -- do not edit by hand. */\n"
        "window.DASH_UPSET_DEMO = " + json.dumps(demos, separators=(",", ":")) + ";\n"
    )
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    build()
